version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - dev-network
    ports:
      - "5002:5000"
      - "5003:5001"
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev-network
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  dev-network:
